// src/pages/my-offers-dashboard/mockData.js

// Helper — generează link Booking automat
const bookingUrl = (destination) =>
  `https://www.booking.com/searchresults.ro.html?ss=${encodeURIComponent(destination)}`;

export const MOCK_DEALS = [
  {
    id: "mock1",
    deal_type: "package",
    title: "City Break Roma – 3 nopți + zbor",
    origin: "București",
    destination: "Roma, Italia",
    image_url: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9",
    rating: 4.7,
    reviews: 1120,
    is_new: true,
    is_saved: false,
    nights: 3,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "Mic dejun",
    departure_date: "2026-03-15",
    return_date: "2026-03-18",
    expiry_date: "2026-02-20",
    booking_url: bookingUrl("Roma Italia"),
    provider: "Booking / Wizz Air",
  },
  {
    id: "mock2",
    deal_type: "package",
    title: "Vacanță Dubai – 5 nopți – hotel 4★ + avion",
    origin: "București",
    destination: "Dubai, EAU",
    image_url: "https://images.unsplash.com/photo-1504274066651-8d31a536b11a",
    rating: 4.8,
    reviews: 820,
    is_new: true,
    is_saved: false,
    nights: 5,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "Mic dejun",
    departure_date: "2026-01-20",
    return_date: "2026-01-25",
    expiry_date: "2025-12-31",
    booking_url: bookingUrl("Dubai"),
    provider: "Booking / FlyDubai",
  },
  {
    id: "mock3",
    deal_type: "package",
    title: "Creta – 7 nopți all-inclusive",
    origin: "Cluj-Napoca",
    destination: "Creta, Grecia",
    image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    rating: 4.6,
    reviews: 560,
    is_new: false,
    is_saved: false,
    nights: 7,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "All inclusive",
    departure_date: "2026-06-10",
    return_date: "2026-06-17",
    expiry_date: "2026-03-01",
    booking_url: bookingUrl("Creta Grecia"),
    provider: "Booking / charter",
  },
  {
    id: "mock4",
    deal_type: "hotel",
    title: "Weekend la Paris – hotel 3★ în centru",
    origin: "București",
    destination: "Paris, Franța",
    image_url: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a",
    rating: 4.3,
    reviews: 740,
    is_new: true,
    is_saved: false,
    nights: 2,
    travelers: 2,
    hotel_stars: 3,
    meal_plan: "Fără masă",
    departure_date: "2026-04-05",
    return_date: "2026-04-07",
    expiry_date: "2026-02-15",
    booking_url: bookingUrl("Paris"),
    provider: "Booking",
  },
  {
    id: "mock5",
    deal_type: "flight",
    title: "Zbor direct București – Londra",
    origin: "București",
    destination: "Londra, UK",
    image_url: "https://images.unsplash.com/photo-1533929736458-ca588d08c8be",
    rating: 4.2,
    reviews: 300,
    is_new: false,
    is_saved: false,
    nights: null,
    travelers: 1,
    hotel_stars: null,
    meal_plan: null,
    departure_date: "2026-02-10",
    return_date: null,
    expiry_date: "2026-01-20",
    booking_url: bookingUrl("Londra"),
    provider: "Ryanair",
  },
  {
    id: "mock6",
    deal_type: "package",
    title: "Maldive – 7 nopți bungalow pe plajă",
    origin: "București",
    destination: "Insulele Maldive",
    image_url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
    rating: 4.9,
    reviews: 980,
    is_new: true,
    is_saved: false,
    nights: 7,
    travelers: 2,
    hotel_stars: 5,
    meal_plan: "All inclusive",
    departure_date: "2026-11-05",
    return_date: "2026-11-12",
    expiry_date: "2026-07-01",
    booking_url: bookingUrl("Maldive"),
    provider: "Booking / Emirates",
  },
  {
    id: "mock7",
    deal_type: "package",
    title: "Istanbul – 4 nopți shopping & city break",
    origin: "București",
    destination: "Istanbul, Turcia",
    image_url: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200",
    rating: 4.4,
    reviews: 640,
    is_new: false,
    is_saved: false,
    nights: 4,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "Mic dejun",
    departure_date: "2026-03-22",
    return_date: "2026-03-26",
    expiry_date: "2026-02-25",
    booking_url: bookingUrl("Istanbul"),
    provider: "Booking / Turkish Airlines",
  },
  {
    id: "mock8",
    deal_type: "hotel",
    title: "City break Berlin – hotel 4★ lângă centru",
    origin: "Cluj-Napoca",
    destination: "Berlin, Germania",
    image_url: "https://images.unsplash.com/photo-1526481280695-3c687fd543c0",
    rating: 4.5,
    reviews: 410,
    is_new: false,
    is_saved: false,
    nights: 3,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "Mic dejun",
    departure_date: "2026-05-18",
    return_date: "2026-05-21",
    expiry_date: "2026-03-30",
    booking_url: bookingUrl("Berlin"),
    provider: "Booking",
  },
  {
    id: "mock9",
    deal_type: "package",
    title: "Zanzibar – 7 nopți pe plajă",
    origin: "București",
    destination: "Zanzibar, Tanzania",
    image_url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
    rating: 4.7,
    reviews: 720,
    is_new: true,
    is_saved: false,
    nights: 7,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "All inclusive",
    departure_date: "2026-09-02",
    return_date: "2026-09-09",
    expiry_date: "2026-05-15",
    booking_url: bookingUrl("Zanzibar"),
    provider: "Booking / Qatar Airways",
  },
  {
    id: "mock10",
    deal_type: "hotel",
    title: "Ski în Austria – 5 nopți la pensiune 3★",
    origin: "București",
    destination: "Tirol, Austria",
    image_url: "https://images.unsplash.com/photo-1519817650390-64a93db511aa",
    rating: 4.3,
    reviews: 380,
    is_new: false,
    is_saved: false,
    nights: 5,
    travelers: 2,
    hotel_stars: 3,
    meal_plan: "Demipensiune",
    departure_date: "2026-01-15",
    return_date: "2026-01-20",
    expiry_date: "2025-12-20",
    booking_url: bookingUrl("Tirol Austria"),
    provider: "Booking",
  },
  {
    id: "mock11",
    deal_type: "package",
    title: "Santorini – 5 nopți view la calderă",
    origin: "București",
    destination: "Santorini, Grecia",
    image_url: "https://images.unsplash.com/photo-1505739771521-9b5071b3aecd",
    rating: 4.8,
    reviews: 880,
    is_new: true,
    is_saved: false,
    nights: 5,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "Mic dejun",
    departure_date: "2026-07-05",
    return_date: "2026-07-10",
    expiry_date: "2026-04-01",
    booking_url: bookingUrl("Santorini"),
    provider: "Booking / charter",
  },
  {
    id: "mock12",
    deal_type: "flight",
    title: "Zbor București – New York (dus-întors)",
    origin: "București",
    destination: "New York, SUA",
    image_url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
    rating: 4.4,
    reviews: 900,
    is_new: false,
    is_saved: false,
    nights: null,
    travelers: 1,
    hotel_stars: null,
    meal_plan: null,
    departure_date: "2026-10-01",
    return_date: "2026-10-10",
    expiry_date: "2026-06-30",
    booking_url: bookingUrl("New York"),
    provider: "Lufthansa",
  },
  {
    id: "mock13",
    deal_type: "package",
    title: "Bali – 8 nopți resort tropical",
    origin: "București",
    destination: "Bali, Indonezia",
    image_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    rating: 4.9,
    reviews: 1100,
    is_new: true,
    is_saved: false,
    nights: 8,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "Mic dejun",
    departure_date: "2026-09-20",
    return_date: "2026-09-28",
    expiry_date: "2026-05-30",
    booking_url: bookingUrl("Bali"),
    provider: "Booking / Qatar",
  },
  {
    id: "mock14",
    deal_type: "hotel",
    title: "Weekend la Viena – hotel 4★ central",
    origin: "Cluj-Napoca",
    destination: "Viena, Austria",
    image_url: "https://images.unsplash.com/photo-1519677100203-a0e668c92439",
    rating: 4.5,
    reviews: 480,
    is_new: false,
    is_saved: false,
    nights: 2,
    travelers: 2,
    hotel_stars: 4,
    meal_plan: "Mic dejun",
    departure_date: "2026-03-08",
    return_date: "2026-03-10",
    expiry_date: "2026-01-31",
    booking_url: bookingUrl("Viena"),
    provider: "Booking",
  },
  {
    id: "mock15",
    deal_type: "package",
    title: "Laponia – 4 nopți, vânătoare de auroră boreală",
    origin: "București",
    destination: "Rovaniemi, Finlanda",
    image_url: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73",
    rating: 4.7,
    reviews: 530,
    is_new: true,
    is_saved: false,
    nights: 4,
    travelers: 2,
    hotel_stars: 3,
    meal_plan: "Demipensiune",
    departure_date: "2026-12-05",
    return_date: "2026-12-09",
    expiry_date: "2026-07-15",
    booking_url: bookingUrl("Rovaniemi Finlanda"),
    provider: "tour operator",
  },
];

export const MOCK_SAVED_SEARCHES = [];
